// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfNhtVjo-qnq5C5A_sEFXcXJUvLenaJ4',
    appId: '1:503890247865:web:cdd6006202b4fa95f91b68',
    messagingSenderId: '503890247865',
    projectId: 'chordmate-10f50',
    authDomain: 'chordmate-10f50.firebaseapp.com',
    storageBucket: 'chordmate-10f50.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08tpz3cWf0kmSJq2_Qnl9TttvZLC3c10',
    appId: '1:503890247865:android:b12a75f199672686f91b68',
    messagingSenderId: '503890247865',
    projectId: 'chordmate-10f50',
    storageBucket: 'chordmate-10f50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYP3FA8elryU5FgWKTQVcOMUoAT0iXAF8',
    appId: '1:503890247865:ios:28fd393ef83c4ed2f91b68',
    messagingSenderId: '503890247865',
    projectId: 'chordmate-10f50',
    storageBucket: 'chordmate-10f50.firebasestorage.app',
    iosBundleId: 'com.example.chordMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYP3FA8elryU5FgWKTQVcOMUoAT0iXAF8',
    appId: '1:503890247865:ios:28fd393ef83c4ed2f91b68',
    messagingSenderId: '503890247865',
    projectId: 'chordmate-10f50',
    storageBucket: 'chordmate-10f50.firebasestorage.app',
    iosBundleId: 'com.example.chordMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXfNhtVjo-qnq5C5A_sEFXcXJUvLenaJ4',
    appId: '1:503890247865:web:eb033d4c1e73fd87f91b68',
    messagingSenderId: '503890247865',
    projectId: 'chordmate-10f50',
    authDomain: 'chordmate-10f50.firebaseapp.com',
    storageBucket: 'chordmate-10f50.firebasestorage.app',
  );
}
